export const details =[
    {
        jo:'1',
        objDetails:{
            contestName:'Active Contest 1',
            questions:[
                {
                    jo:'1',
                    name:'abhb',
                    max_score:'50',
                    difficulty:'easy',
                    isSolved:true
                },
                {
                    jo:'2',
                    name:'',
                    max_score:'100',
                    difficulty:'hard',
                    isSolved:false
                },
            ]
        }
    },
    {
        jo:'2',
        objDetails:{
            contestName:'Active Contest 2',
            questions:[
                {
                    jo:'1',
                    name:'xyz',
                    max_score:'50',
                    difficulty:'medium',
                    isSolved:false
                },
                {
                    jo:'2',
                    name:'abc',
                    max_score:'25',
                    difficulty:'easy',
                    isSolved:false
                },
            ]
        }
    }
]