export const internships = [
  {
    jo: 1,
    objDetails: {
      logo: "https://placehold.co/80x80",
      internPost: "Software Engineer",
      companyName: "ABC Company",
      location: "New York, USA",
      internType: "Full Time",
      salary: "$123-$456",
      date: "01 Jan, 2045",
    },
  },
  {
    jo: 2,
    objDetails: {
      logo: "https://placehold.co/80x80",
      internPost: "Marketing Engineer",
      companyName: "ABC Company",
      location: "New York, USA",
      internType: "Full Time",
      salary: "$123-$456",
      date: "01 Jan, 2045",
    },
  },
  {
    jo: 3,
    objDetails: {
      logo: "https://placehold.co/80x80",
      internPost: "SQL Developer",
      companyName: "ABC Company",
      location: "New York, USA",
      internType: "Part Time",
      salary: "$123-$456",
      date: "01 Jan, 2045",
    },
  },
  {
    jo: 4,
    objDetails: {
      logo: "https://placehold.co/80x80",
      internPost: "Full Stack Engineer",
      companyName: "ABC Company",
      location: "New York, USA",
      internType: "Full Time",
      salary: "$123-$456",
      date: "01 Jan, 2045",
    },
  },
  {
    jo: 5,
    objDetails: {
      logo: "https://placehold.co/80x80",
      internPost: "Web Developer",
      companyName: "ABC Company",
      location: "New York, USA",
      internType: "Full Time",
      salary: "$123-$456",
      date: "01 Jan, 2045",
    },
  },
  {
    jo: 6,
    objDetails: {
      logo: "https://placehold.co/80x80",
      internPost: "Web Designer",
      companyName: "ABC Company",
      location: "New York, USA",
      internType: "Part Time",
      salary: "$123-$456",
      date: "01 Jan, 2045",
    },
  },
  {
    jo: 7,
    objDetails: {
      logo: "https://placehold.co/80x80",
      internPost: "React Developer",
      companyName: "ABC Company",
      location: "New York, USA",
      internType: "Full Time",
      salary: "$123-$456",
      date: "01 Jan, 2045",
    },
  },
  {
    jo: 8,
    objDetails: {
      logo: "https://placehold.co/80x80",
      internPost: "Java Developer",
      companyName: "ABC Company",
      location: "New York, USA",
      internType: "Part Time",
      salary: "$123-$456",
      date: "01 Jan, 2045",
    },
  },
  {
    jo: 9,
    objDetails: {
      logo: "https://placehold.co/80x80",
      internPost: "UI/UX Designer",
      companyName: "ABC Company",
      location: "New York, USA",
      internType: "Full Time",
      salary: "$123-$456",
      date: "01 Jan, 2045",
    },
  },
  {
    jo: 10,
    objDetails: {
      logo: "https://placehold.co/80x80",
      internPost: "Php Developer",
      companyName: "ABC Company",
      location: "New York, USA",
      internType: "Part Time",
      salary: "$123-$456",
      date: "01 Jan, 2045",
    },
  },
];
